name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-20.04
    services:
      world:
        image: sem-world
        ports:
          - "33060:3306"
        environment:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: world
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=30s 
          --health-timeout=10s 
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn clean package
      - name: Run Docker Compose
        run: docker-compose up --abort-on-container-exit
      - name: View Logs
        run: |
          echo "Fetching logs from semethods-app-1..."
          docker logs semethods-app-1 || echo "No logs available for semethods-app-1"
      - name: Copy Output
        run: docker container cp semethods-app-1:./tmp/output ./
      - name: List directories
        run: |
          echo "Current directory structure:"
          pwd
          ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
