name: A workflow for my App
on: push

jobs:
  build:
    name: Test Build Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Debug Info
        run: |
          java -version
          mvn -version
          ls -la

      - name: Unit Tests
        run: |
          echo "Running tests..."
          mvn clean test -Dtest=com.napier.sem.AppTest -X

      - name: Package and Run docker compose
        if: success()
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

      - name: view logs
        if: always()
        run: docker logs devops3-app-1 || true

      - name: Copy Output
        if: success()
        run: docker container cp devops3-app-1:./tmp/output ./ || true

      - name: List dirs
        if: always()
        run: |
          pwd
          ls -la

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output