name: A workflow for my App

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Test Build Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Unit Tests
        run: mvn test

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          sudo apt-get install -y docker-compose

      - name: Check Docker Compose version
        run: docker-compose --version  # Verify Docker Compose installation

      - name: Package and Run docker compose
        run: |
          mvn package
          docker-compose up --abort-on-container-exit
